package com.stopforfuel.backend.service;

import com.stopforfuel.backend.entity.InvoiceBill;
import com.stopforfuel.backend.entity.InvoiceProduct;
import com.stopforfuel.backend.entity.Product;
import com.stopforfuel.backend.entity.Shift;
import com.stopforfuel.backend.enums.BillType;
import com.stopforfuel.backend.enums.PaymentMode;
import com.stopforfuel.backend.enums.PaymentStatus;
import com.stopforfuel.backend.enums.ShiftStatus;
import com.stopforfuel.backend.repository.InvoiceBillRepository;
import com.stopforfuel.backend.repository.ShiftRepository;
import com.stopforfuel.config.SecurityUtils;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.EnumSet;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Creates synthetic cash invoices at shift close to cover the residual
 * "cash-in-till" fuel that wasn't explicitly invoiced by the cashier.
 *
 * Credit invoices are cashier-raised (their accountability); cash invoices are
 * often skipped because most cash sales are small walk-ins. Without synthetic
 * bills, the invoice_bill table under-represents cash revenue — breaking any
 * downstream audit that rolls up invoices.
 *
 * Per fuel product, per shift:
 *   residualQty = meter_net_litres − Σ InvoiceProduct.quantity (all existing invoices)
 * If residualQty > 0 → create one CASH invoice with that product + quantity.
 *
 * Idempotent: wipes any existing autoGenerated bills for the shift first, so
 * reopen/close cycles don't double-count.
 *
 * Bypasses {@link InvoiceBillService#createInvoice(InvoiceBill)} on purpose —
 * we don't want its side effects (tank dip decrement, nozzle meter increment,
 * incentive payments) because synthetic bills represent physical fuel already
 * reflected in the meter/dip readings.
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class ShiftCashInvoiceAutoService {

    private static final BigDecimal RESIDUAL_EPSILON = new BigDecimal("0.01"); // 10 mL

    private final InvoiceBillRepository invoiceBillRepository;
    private final ShiftRepository shiftRepository;
    private final ShiftSalesCalculationService salesCalc;
    private final BillSequenceService billSequenceService;

    /**
     * Generate synthetic cash invoices for every fuel product with unaccounted
     * residual in the given shift. Safe to re-call (wipes prior autos first).
     */
    @Transactional
    public List<InvoiceBill> generateForShift(Long shiftId) {
        if (shiftId == null) return List.of();

        Shift shift = shiftRepository.findById(shiftId).orElse(null);
        if (shift == null) {
            log.warn("generateForShift: shift {} not found", shiftId);
            return List.of();
        }

        // Idempotency: drop any prior autos for this shift.
        int wiped = invoiceBillRepository.deleteByShiftIdAndAutoGeneratedTrue(shiftId);
        if (wiped > 0) log.info("Wiped {} prior synthetic cash invoices for shift {}", wiped, shiftId);

        // 1) meter-based fuel totals per product (net = sales − test)
        Map<Long, ShiftSalesCalculationService.FuelSaleAggregate> fuelByProduct =
                salesCalc.computeFuelSalesByProduct(shiftId);
        if (fuelByProduct.isEmpty()) return List.of();

        // 2) already-invoiced quantity per product from the shift's existing invoices
        Map<Long, BigDecimal> invoicedQtyByProduct = invoicedQuantityByProduct(shiftId);

        // 3) for each product, compute residual and build an invoice
        List<InvoiceBill> created = new ArrayList<>();
        for (ShiftSalesCalculationService.FuelSaleAggregate agg : fuelByProduct.values()) {
            if (agg.getProduct() == null || agg.getNetLitres() <= 0) continue;

            BigDecimal meterQty = BigDecimal.valueOf(agg.getNetLitres()).setScale(4, RoundingMode.HALF_UP);
            BigDecimal invoicedQty = invoicedQtyByProduct.getOrDefault(agg.getProduct().getId(), BigDecimal.ZERO);
            BigDecimal residualQty = meterQty.subtract(invoicedQty);

            if (residualQty.compareTo(RESIDUAL_EPSILON) <= 0) {
                if (residualQty.signum() < 0) {
                    log.warn("Shift {} product {} ({}): over-invoiced by {} L (meter={}, invoiced={}). Skipped synthetic.",
                            shiftId, agg.getProduct().getId(), agg.getProduct().getName(),
                            residualQty.abs(), meterQty, invoicedQty);
                }
                continue;
            }

            InvoiceBill bill = buildSyntheticBill(shift, agg.getProduct(), residualQty, agg.getRate());
            InvoiceBill saved = invoiceBillRepository.save(bill);
            created.add(saved);
            log.info("Shift {} product {}: synthetic {} for {} L @ ₹{} = ₹{}",
                    shiftId, agg.getProduct().getName(), saved.getBillNo(),
                    residualQty, agg.getRate(), saved.getNetAmount());
        }
        return created;
    }

    /**
     * One-shot backfill — iterate all CLOSED or RECONCILED shifts in [from, to]
     * for the current scid and regenerate synthetic cash invoices.
     * Returns a per-shift summary for admin inspection.
     */
    @Transactional
    public Map<String, Object> backfillRange(LocalDate from, LocalDate to) {
        Long scid = SecurityUtils.getScid();
        List<Shift> shifts = shiftRepository.findByScidAndStartTimeBetweenOrderByStartTimeAsc(
                scid, from.atStartOfDay(), to.atTime(LocalTime.MAX));

        List<Map<String, Object>> perShift = new ArrayList<>();
        List<Map<String, Object>> failures = new ArrayList<>();
        int processed = 0;
        int invoicesCreated = 0;
        BigDecimal totalAmount = BigDecimal.ZERO;

        EnumSet<ShiftStatus> eligible = EnumSet.of(ShiftStatus.CLOSED, ShiftStatus.RECONCILED);
        for (Shift shift : shifts) {
            if (shift.getStatus() == null || !eligible.contains(shift.getStatus())) continue;
            processed++;
            try {
                List<InvoiceBill> created = generateForShift(shift.getId());
                BigDecimal shiftAmount = BigDecimal.ZERO;
                for (InvoiceBill b : created) {
                    if (b.getNetAmount() != null) shiftAmount = shiftAmount.add(b.getNetAmount());
                }
                invoicesCreated += created.size();
                totalAmount = totalAmount.add(shiftAmount);

                Map<String, Object> row = new LinkedHashMap<>();
                row.put("shiftId", shift.getId());
                row.put("startTime", shift.getStartTime());
                row.put("invoicesCreated", created.size());
                row.put("amount", shiftAmount);
                perShift.add(row);
            } catch (Exception e) {
                log.error("Backfill failed for shift {}", shift.getId(), e);
                Map<String, Object> fail = new LinkedHashMap<>();
                fail.put("shiftId", shift.getId());
                fail.put("error", e.getMessage());
                failures.add(fail);
            }
        }

        Map<String, Object> summary = new LinkedHashMap<>();
        summary.put("from", from.toString());
        summary.put("to", to.toString());
        summary.put("shiftsProcessed", processed);
        summary.put("invoicesCreated", invoicesCreated);
        summary.put("totalAmount", totalAmount);
        summary.put("perShift", perShift);
        summary.put("failures", failures);
        return summary;
    }

    private Map<Long, BigDecimal> invoicedQuantityByProduct(Long shiftId) {
        // invoiceBills for the shift are already small in count; fetch with products eagerly loaded
        List<InvoiceBill> existing = invoiceBillRepository.findByShiftIdOrderByIdDesc(shiftId);
        Map<Long, BigDecimal> qtyByProduct = new HashMap<>();
        for (InvoiceBill bill : existing) {
            if (bill.isAutoGenerated()) continue; // safety — should already be wiped
            if (bill.getProducts() == null) continue;
            for (InvoiceProduct ip : bill.getProducts()) {
                if (ip.getProduct() == null || ip.getProduct().getId() == null || ip.getQuantity() == null) continue;
                qtyByProduct.merge(ip.getProduct().getId(), ip.getQuantity(), BigDecimal::add);
            }
        }
        return qtyByProduct;
    }

    private InvoiceBill buildSyntheticBill(Shift shift, Product product,
                                           BigDecimal quantity, double rate) {
        BigDecimal unitPrice = BigDecimal.valueOf(rate).setScale(4, RoundingMode.HALF_UP);
        BigDecimal amount = quantity.multiply(unitPrice).setScale(4, RoundingMode.HALF_UP);

        InvoiceBill bill = new InvoiceBill();
        bill.setBillType(BillType.CASH);
        bill.setPaymentMode(PaymentMode.CASH);
        bill.setPaymentStatus(PaymentStatus.PAID);
        bill.setStatus("PAID");
        bill.setShiftId(shift.getId());
        bill.setScid(shift.getScid());
        bill.setGrossAmount(amount);
        bill.setTotalDiscount(BigDecimal.ZERO);
        bill.setNetAmount(amount);
        bill.setAutoGenerated(true);
        bill.setBillDesc("Auto — shift " + shift.getId() + " residual cash sale");
        bill.setDate(shift.getEndTime() != null ? shift.getEndTime() : java.time.LocalDateTime.now());
        bill.setBillNo(billSequenceService.getNextBillNo(BillType.CASH));

        InvoiceProduct ip = new InvoiceProduct();
        ip.setInvoiceBill(bill);
        ip.setProduct(product);
        ip.setQuantity(quantity);
        ip.setUnitPrice(unitPrice);
        ip.setGrossAmount(amount);
        ip.setDiscountAmount(BigDecimal.ZERO);
        ip.setAmount(amount);
        bill.getProducts().add(ip);

        return bill;
    }
}
