package com.stopforfuel.backend.service;

import com.stopforfuel.backend.entity.InvoiceBill;
import com.stopforfuel.backend.entity.InvoiceProduct;
import com.stopforfuel.backend.entity.Product;
import com.stopforfuel.backend.entity.Shift;
import com.stopforfuel.backend.enums.BillType;
import com.stopforfuel.backend.enums.ShiftStatus;
import com.stopforfuel.backend.repository.InvoiceBillRepository;
import com.stopforfuel.backend.repository.ShiftRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.math.BigDecimal;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyLong;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class ShiftCashInvoiceAutoServiceTest {

    @Mock private InvoiceBillRepository invoiceBillRepository;
    @Mock private ShiftRepository shiftRepository;
    @Mock private ShiftSalesCalculationService salesCalc;
    @Mock private BillSequenceService billSequenceService;

    @InjectMocks private ShiftCashInvoiceAutoService service;

    private Shift shift;
    private Product petrol;
    private Product diesel;

    @BeforeEach
    void setUp() {
        shift = new Shift();
        shift.setId(100L);
        shift.setScid(1L);
        shift.setStatus(ShiftStatus.CLOSED);

        petrol = new Product();
        petrol.setId(1L);
        petrol.setName("Petrol");
        petrol.setPrice(new BigDecimal("100.00"));
        petrol.setCategory("FUEL");

        diesel = new Product();
        diesel.setId(2L);
        diesel.setName("Diesel");
        diesel.setPrice(new BigDecimal("90.00"));
        diesel.setCategory("FUEL");
    }

    @Test
    void generateForShift_positiveResidual_createsOneBillPerProductWithResidualQty() {
        when(shiftRepository.findById(100L)).thenReturn(Optional.of(shift));
        when(invoiceBillRepository.deleteByShiftIdAndAutoGeneratedTrue(100L)).thenReturn(0);

        // meter: petrol 500 L, diesel 300 L
        Map<Long, ShiftSalesCalculationService.FuelSaleAggregate> fuel = new LinkedHashMap<>();
        ShiftSalesCalculationService.FuelSaleAggregate pAgg =
                new ShiftSalesCalculationService.FuelSaleAggregate(petrol, 100.0);
        pAgg.getClass(); // avoid unused warning
        // Reflect on non-final fields via package-private setters — the aggregate exposes getters only,
        // so use the constructor path: we need to prime netLitres. Use a helper construction pattern:
        fuel.put(1L, aggregate(petrol, 500.0, 0.0, 100.0));
        fuel.put(2L, aggregate(diesel, 300.0, 0.0, 90.0));
        when(salesCalc.computeFuelSalesByProduct(100L)).thenReturn(fuel);

        // Existing invoices: petrol credit 200 L, diesel credit 50 L
        InvoiceBill petrolCredit = billWith(petrol, new BigDecimal("200"), BillType.CREDIT, false);
        InvoiceBill dieselCredit = billWith(diesel, new BigDecimal("50"), BillType.CREDIT, false);
        when(invoiceBillRepository.findByShiftIdOrderByIdDesc(100L))
                .thenReturn(List.of(petrolCredit, dieselCredit));

        when(billSequenceService.getNextBillNo(BillType.CASH))
                .thenReturn("C26/10", "C26/11");
        when(invoiceBillRepository.save(any(InvoiceBill.class))).thenAnswer(i -> i.getArgument(0));

        List<InvoiceBill> created = service.generateForShift(100L);

        assertEquals(2, created.size());

        ArgumentCaptor<InvoiceBill> captor = ArgumentCaptor.forClass(InvoiceBill.class);
        verify(invoiceBillRepository, times(2)).save(captor.capture());
        List<InvoiceBill> saved = captor.getAllValues();

        InvoiceBill p = saved.stream().filter(b -> "C26/10".equals(b.getBillNo())).findFirst().orElseThrow();
        assertTrue(p.isAutoGenerated());
        assertEquals(BillType.CASH, p.getBillType());
        assertNull(p.getCustomer());
        assertEquals(1, p.getProducts().size());
        assertEquals(new BigDecimal("300.0000"), p.getProducts().get(0).getQuantity());
        assertEquals(0, p.getNetAmount().compareTo(new BigDecimal("30000")));

        InvoiceBill d = saved.stream().filter(b -> "C26/11".equals(b.getBillNo())).findFirst().orElseThrow();
        assertEquals(new BigDecimal("250.0000"), d.getProducts().get(0).getQuantity());
        assertEquals(0, d.getNetAmount().compareTo(new BigDecimal("22500")));
    }

    @Test
    void generateForShift_negativeResidual_skipsBill() {
        when(shiftRepository.findById(100L)).thenReturn(Optional.of(shift));
        when(invoiceBillRepository.deleteByShiftIdAndAutoGeneratedTrue(100L)).thenReturn(0);

        // meter: petrol 100 L, but cashier invoiced 150 L (credit) — residual negative
        Map<Long, ShiftSalesCalculationService.FuelSaleAggregate> fuel = new LinkedHashMap<>();
        fuel.put(1L, aggregate(petrol, 100.0, 0.0, 100.0));
        when(salesCalc.computeFuelSalesByProduct(100L)).thenReturn(fuel);

        InvoiceBill overInvoiced = billWith(petrol, new BigDecimal("150"), BillType.CREDIT, false);
        when(invoiceBillRepository.findByShiftIdOrderByIdDesc(100L)).thenReturn(List.of(overInvoiced));

        List<InvoiceBill> created = service.generateForShift(100L);

        assertEquals(0, created.size());
        verify(invoiceBillRepository, never()).save(any());
        verify(billSequenceService, never()).getNextBillNo(any());
    }

    @Test
    void generateForShift_idempotent_wipesPriorAutosFirst() {
        when(shiftRepository.findById(100L)).thenReturn(Optional.of(shift));
        when(invoiceBillRepository.deleteByShiftIdAndAutoGeneratedTrue(100L)).thenReturn(3);
        when(salesCalc.computeFuelSalesByProduct(100L)).thenReturn(Map.of());

        service.generateForShift(100L);

        verify(invoiceBillRepository).deleteByShiftIdAndAutoGeneratedTrue(100L);
    }

    @Test
    void generateForShift_nullShiftId_returnsEmpty() {
        assertTrue(service.generateForShift(null).isEmpty());
        verifyNoInteractions(invoiceBillRepository, salesCalc, billSequenceService);
    }

    @Test
    void generateForShift_shiftNotFound_returnsEmpty() {
        when(shiftRepository.findById(999L)).thenReturn(Optional.empty());
        assertTrue(service.generateForShift(999L).isEmpty());
        verify(invoiceBillRepository, never()).deleteByShiftIdAndAutoGeneratedTrue(anyLong());
    }

    @Test
    void generateForShift_excludesExistingAutoBillsFromInvoicedSum() {
        when(shiftRepository.findById(100L)).thenReturn(Optional.of(shift));
        when(invoiceBillRepository.deleteByShiftIdAndAutoGeneratedTrue(100L)).thenReturn(0);

        Map<Long, ShiftSalesCalculationService.FuelSaleAggregate> fuel = new LinkedHashMap<>();
        fuel.put(1L, aggregate(petrol, 500.0, 0.0, 100.0));
        when(salesCalc.computeFuelSalesByProduct(100L)).thenReturn(fuel);

        // One real credit (100 L), one leftover auto (200 L — should be ignored)
        InvoiceBill real = billWith(petrol, new BigDecimal("100"), BillType.CREDIT, false);
        InvoiceBill leftoverAuto = billWith(petrol, new BigDecimal("200"), BillType.CASH, true);
        when(invoiceBillRepository.findByShiftIdOrderByIdDesc(100L)).thenReturn(List.of(real, leftoverAuto));

        when(billSequenceService.getNextBillNo(BillType.CASH)).thenReturn("C26/20");
        when(invoiceBillRepository.save(any(InvoiceBill.class))).thenAnswer(i -> i.getArgument(0));

        List<InvoiceBill> created = service.generateForShift(100L);

        assertEquals(1, created.size());
        // Residual = 500 − 100 (real only) = 400
        assertEquals(new BigDecimal("400.0000"), created.get(0).getProducts().get(0).getQuantity());
    }

    // -------- helpers --------

    private ShiftSalesCalculationService.FuelSaleAggregate aggregate(
            Product product, double netLitres, double testLitres, double rate) {
        ShiftSalesCalculationService.FuelSaleAggregate agg =
                new ShiftSalesCalculationService.FuelSaleAggregate(product, rate);
        // netLitres & testLitres are package-private mutable in the aggregate — use reflection
        try {
            java.lang.reflect.Field nf = agg.getClass().getDeclaredField("netLitres");
            nf.setAccessible(true);
            nf.setDouble(agg, netLitres);
            java.lang.reflect.Field tf = agg.getClass().getDeclaredField("testLitres");
            tf.setAccessible(true);
            tf.setDouble(agg, testLitres);
        } catch (ReflectiveOperationException e) {
            throw new RuntimeException(e);
        }
        return agg;
    }

    private InvoiceBill billWith(Product p, BigDecimal qty, BillType type, boolean auto) {
        InvoiceBill b = new InvoiceBill();
        b.setBillType(type);
        b.setAutoGenerated(auto);
        InvoiceProduct ip = new InvoiceProduct();
        ip.setProduct(p);
        ip.setQuantity(qty);
        b.getProducts().add(ip);
        return b;
    }
}
