app:
  auth:
    enabled: false
  seed-test-data:
    enabled: true

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.oauth2.resource.servlet.OAuth2ResourceServerAutoConfiguration
